trigger:
- main

pool:
  name: 'digitalocean'

variables:
  emailvar: 'vp@company.com' # Replace with your email
  clusternamevar: 'product1kubernetes' # Replace with your cluster name
  ipsvar: '157.230.117.175 207.154.230.157 164.90.209.3' # Replace with your IPs

stages:
- stage: DeployKubernetes
  jobs:
  - job: InstallKubernetes
    steps:
    - script: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible git python3-pip python3-venv
      displayName: 'Install dependencies'

    - script: |
        ssh-keygen -t ed25519 -C "$emailvar" -f ~/.ssh/$clusternamevar -N $clusternamevar
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/$clusternamevar
      displayName: 'Generate SSH keys'

    - script: |
        ips=($ipsvar)
        for ip in "${ips[@]}"; do
          ssh-copy-id -f -i ~/.ssh/$clusternamevar.pub -o "IdentityFile ~/.ssh/digitalocean" root@$ip
        done
      displayName: 'Set up SSH access for all nodes'

    - script: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible
        ansible --version
      displayName: 'Install Ansible'

    - script: |
        git clone https://github.com/kubernetes-sigs/kubespray.git
        cd kubespray/
        sudo swapoff -a
        sudo ufw disable
        sudo systemctl disable ufw
        sudo apt install -y aufs-tools python3-pip python3-venv build-essential libssl-dev libffi-dev python-dev
        sudo apt-get update -y
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install ruamel.yaml
      displayName: 'Clone and prepare Kubespray'

    - script: |
        mkdir -p kubespray/inventory/$clusternamevar
        cp -r kubespray/inventory/sample/* kubespray/inventory/$clusternamevar/
        declare -a IPS=($ipsvar)
        CONFIG_FILE=kubespray/inventory/$clusternamevar/hosts.yaml python3 kubespray/contrib/inventory_builder/inventory.py ${IPS[@]}
      displayName: 'Set up Kubespray inventory'

    - script: |
        ansible-playbook -i kubespray/inventory/$clusternamevar/hosts.yaml --become --become-user=root kubespray/cluster.yml
      displayName: 'Deploy Kubernetes with Kubespray'

