pool:
  name: 'digitalocean'

variables:
  clusternamevar: 'product1kubernetes' # Replace with your cluster name
  ipsvar: '157.230.121.63 138.68.100.202' # Replace with your IPs
  vmprivatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDZN18O1q
    naZl21iHkgK7e6AAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIMdQPl+eVCJzGX7v
    RebWo/qstk4Bxa2MAA5WlBuASRaBAAAAoOvxHldQBjD3XviXqD30o9tA+wWRltUTuo74lL
    8XWCG6hRhlTy3286jVIeJOQf0gC1/hiCnUbvQ1N669zuk/cBVGMc8V6ASkJZprtzzX7Zrh
    7AIT5he5RAPj96Ma6rRrwgXpWg4E+lMN5NzRpUmfnr3HAdmt0Nvkq/vKOKOIPZNya4pZ58
    u91r9hbNeMWWNBaA47PRRXk2oXySHGjRa8wg8=
    -----END OPENSSH PRIVATE KEY-----
  vmpassphrase: 'digitalocean'

stages:
- stage: DeployKubernetes
  jobs:
  - job: InstallKubernetes
    steps:
    - script: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository --yes --update ppa:ansible/ansible
        sudo apt install -y ansible git python3-pip python3-venv
        sudo apt install expect
      displayName: 'Install dependencies'

    - script: |
        sudo rm -f /home/azureagent/.ssh/vm_private_key
        # echo $(vmprivatekey) >> /home/azureagent/.ssh/vm_private_key
        cat << 'EOF' > /home/azureagent/.ssh/vm_private_key
        $(vmprivatekey)
        EOF
        chmod 600 /home/azureagent/.ssh/vm_private_key
        chown root:root /home/azureagent/.ssh/vm_private_key
        # It is required that your private key files are NOT accessible by others.
        ips=($(ipsvar))

        eval "$(ssh-agent -s)"
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> ~/.ssh/environment
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> ~/.ssh/environment
        source ~/.ssh/environment

        # Create the expect script
        cat << 'EOF' > add_ssh_key.exp
        #!/usr/bin/expect -f
        set timeout -1
        set key_path [lindex $argv 0]
        set passphrase [lindex $argv 1]
        spawn ssh-add $key_path
        expect "Enter passphrase for"
        send "$passphrase\r"
        expect eof
        EOF

        # Make the script executable
        chmod +x add_ssh_key.exp

        # Run the expect script with the SSH key and passphrase
        ./add_ssh_key.exp /home/azureagent/.ssh/vm_private_key "$(vmpassphrase)"
      displayName: 'Set up SSH access for all nodes'
    
    - script: |
        sudo swapoff -a
        sudo ufw disable
        sudo systemctl disable ufw
      displayName: 'Disable Firewall'

    - script: |
        git clone https://github.com/kubernetes-sigs/kubespray.git
        cd kubespray/
        python3 -m venv venv
        source venv/bin/activate
        pip3 install -r requirements.txt
        pip3 install ruamel.yaml
      displayName: 'Clone and prepare Kubespray'

    - script: |
        mkdir -p kubespray/inventory/$(clusternamevar)
        cp -r kubespray/inventory/sample/* kubespray/inventory/$(clusternamevar)/
        source kubespray/venv/bin/activate
        declare -a IPS=($(ipsvar))
        CONFIG_FILE=kubespray/inventory/$(clusternamevar)/hosts.yaml python3 kubespray/contrib/inventory_builder/inventory.py ${IPS[@]}
      displayName: 'Set up Kubespray inventory'

    - script: |
        cd kubespray
        source venv/bin/activate
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -i inventory/$(clusternamevar)/hosts.yaml -u root --private-key=/home/azureagent/.ssh/vm_private_key --become --become-user=root cluster.yml
      displayName: 'Deploy Kubernetes with Kubespray'

